spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/wc_team_info_db
    password: rafeed2030
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
app:
  jwt:
    secret: m@$T3rp@$$

server:
  port: 8085